#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
controllers:
    resource: ../src/Controller/
    type: annotation

test_hello:
    path:  /
    defaults: { _controller: 'App\Controller\HelloController::hello' }